spring.application.name=optica

server.port=8085

#spring.jpa.hibernate.ddl-auto=create
spring.datasource.url=jdbc:mysql://localhost:3306/optica
spring.datasource.username=root
spring.datasource.password=esteban83
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.show-sql: true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.naming-strategy=org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect
#spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect


security.jwt.key = fd85f40e8e4f1a7914cf7c77c6b505004627fbb5ad913d7a97e664e22d1432d3f1e65d6ccaa8a554a7b3b9f498df8b1efedeabf089fbeaf30bf5e811c599c642
security.jwt.expiration = 360000000000

company.name = Optica