INSERT INTO optica.canton
(id, id_provincia, nombre)
VALUES(1, 1, 'CUENCA');
INSERT INTO optica.canton
(id, id_provincia, nombre)
VALUES(2, 1, 'GIRÓN');
INSERT INTO optica.canton
(id, id_provincia, nombre)
VALUES(3, 1, 'GUALACEO');
INSERT INTO optica.canton
(id, id_provincia, nombre)
VALUES(4, 1, 'NABÓN');
INSERT INTO optica.canton
(id, id_provincia, nombre)
VALUES(5, 1, 'PAUTE');
INSERT INTO optica.canton
(id, id_provincia, nombre)
VALUES(6, 1, 'PUCARA');
INSERT INTO optica.canton
(id, id_provincia, nombre)
VALUES(7, 1, 'SAN FERNANDO');
INSERT INTO optica.canton
(id, id_provincia, nombre)
VALUES(8, 1, 'SANTA ISABEL');
INSERT INTO optica.canton
(id, id_provincia, nombre)
VALUES(9, 1, 'SIGSIG');
INSERT INTO optica.canton
(id, id_provincia, nombre)
VALUES(10, 1, 'OÑA');
INSERT INTO optica.canton
(id, id_provincia, nombre)
VALUES(11, 1, 'CHORDELEG');
INSERT INTO optica.canton
(id, id_provincia, nombre)
VALUES(12, 1, 'EL PAN');
INSERT INTO optica.canton
(id, id_provincia, nombre)
VALUES(13, 1, 'SEVILLA DE ORO');
INSERT INTO optica.canton
(id, id_provincia, nombre)
VALUES(14, 1, 'GUACHAPALA');
INSERT INTO optica.canton
(id, id_provincia, nombre)
VALUES(15, 1, 'CAMILO PONCE ENRÍQUEZ');
INSERT INTO optica.canton
(id, id_provincia, nombre)
VALUES(16, 2, 'GUARANDA');
INSERT INTO optica.canton
(id, id_provincia, nombre)
VALUES(17, 2, 'CHILLANES');
INSERT INTO optica.canton
(id, id_provincia, nombre)
VALUES(18, 2, 'CHIMBO');
INSERT INTO optica.canton
(id, id_provincia, nombre)
VALUES(19, 2, 'ECHEANDÍA');
INSERT INTO optica.canton
(id, id_provincia, nombre)
VALUES(20, 2, 'SAN MIGUEL');
INSERT INTO optica.canton
(id, id_provincia, nombre)
VALUES(21, 2, 'CALUMA');
INSERT INTO optica.canton
(id, id_provincia, nombre)
VALUES(22, 2, 'LAS NAVES');
INSERT INTO optica.canton
(id, id_provincia, nombre)
VALUES(23, 3, 'AZOGUES');
INSERT INTO optica.canton
(id, id_provincia, nombre)
VALUES(24, 3, 'BIBLIÁN');
INSERT INTO optica.canton
(id, id_provincia, nombre)
VALUES(25, 3, 'CAÑAR');
INSERT INTO optica.canton
(id, id_provincia, nombre)
VALUES(26, 3, 'LA TRONCAL');
INSERT INTO optica.canton
(id, id_provincia, nombre)
VALUES(27, 3, 'EL TAMBO');
INSERT INTO optica.canton
(id, id_provincia, nombre)
VALUES(28, 3, 'DÉLEG');
INSERT INTO optica.canton
(id, id_provincia, nombre)
VALUES(29, 3, 'SUSCAL');
INSERT INTO optica.canton
(id, id_provincia, nombre)
VALUES(30, 4, 'TULCÁN');
INSERT INTO optica.canton
(id, id_provincia, nombre)
VALUES(31, 4, 'BOLÍVAR');
INSERT INTO optica.canton
(id, id_provincia, nombre)
VALUES(32, 4, 'ESPEJO');
INSERT INTO optica.canton
(id, id_provincia, nombre)
VALUES(33, 4, 'MIRA');
INSERT INTO optica.canton
(id, id_provincia, nombre)
VALUES(34, 4, 'MONTÚFAR');
INSERT INTO optica.canton
(id, id_provincia, nombre)
VALUES(35, 4, 'SAN PEDRO DE HUACA');
INSERT INTO optica.canton
(id, id_provincia, nombre)
VALUES(36, 5, 'LATACUNGA');
INSERT INTO optica.canton
(id, id_provincia, nombre)
VALUES(37, 5, 'LA MANÁ');
INSERT INTO optica.canton
(id, id_provincia, nombre)
VALUES(38, 5, 'PANGUA');
INSERT INTO optica.canton
(id, id_provincia, nombre)
VALUES(39, 5, 'PUJILI');
INSERT INTO optica.canton
(id, id_provincia, nombre)
VALUES(40, 5, 'SALCEDO');
INSERT INTO optica.canton
(id, id_provincia, nombre)
VALUES(41, 5, 'SAQUISILÍ');
INSERT INTO optica.canton
(id, id_provincia, nombre)
VALUES(42, 5, 'SIGCHOS');
INSERT INTO optica.canton
(id, id_provincia, nombre)
VALUES(43, 6, 'RIOBAMBA');
INSERT INTO optica.canton
(id, id_provincia, nombre)
VALUES(44, 6, 'ALAUSI');
INSERT INTO optica.canton
(id, id_provincia, nombre)
VALUES(45, 6, 'COLTA');
INSERT INTO optica.canton
(id, id_provincia, nombre)
VALUES(46, 6, 'CHAMBO');
INSERT INTO optica.canton
(id, id_provincia, nombre)
VALUES(47, 6, 'CHUNCHI');
INSERT INTO optica.canton
(id, id_provincia, nombre)
VALUES(48, 6, 'GUAMOTE');
INSERT INTO optica.canton
(id, id_provincia, nombre)
VALUES(49, 6, 'GUANO');
INSERT INTO optica.canton
(id, id_provincia, nombre)
VALUES(50, 6, 'PALLATANGA');
INSERT INTO optica.canton
(id, id_provincia, nombre)
VALUES(51, 6, 'PENIPE');
INSERT INTO optica.canton
(id, id_provincia, nombre)
VALUES(52, 6, 'CUMANDÁ');
INSERT INTO optica.canton
(id, id_provincia, nombre)
VALUES(53, 7, 'MACHALA');
INSERT INTO optica.canton
(id, id_provincia, nombre)
VALUES(54, 7, 'ARENILLAS');
INSERT INTO optica.canton
(id, id_provincia, nombre)
VALUES(55, 7, 'ATAHUALPA');
INSERT INTO optica.canton
(id, id_provincia, nombre)
VALUES(56, 7, 'BALSAS');
INSERT INTO optica.canton
(id, id_provincia, nombre)
VALUES(57, 7, 'CHILLA');
INSERT INTO optica.canton
(id, id_provincia, nombre)
VALUES(58, 7, 'EL GUABO');
INSERT INTO optica.canton
(id, id_provincia, nombre)
VALUES(59, 7, 'HUAQUILLAS');
INSERT INTO optica.canton
(id, id_provincia, nombre)
VALUES(60, 7, 'MARCABELÍ');
INSERT INTO optica.canton
(id, id_provincia, nombre)
VALUES(61, 7, 'PASAJE');
INSERT INTO optica.canton
(id, id_provincia, nombre)
VALUES(62, 7, 'PIÑAS');
INSERT INTO optica.canton
(id, id_provincia, nombre)
VALUES(63, 7, 'PORTOVELO');
INSERT INTO optica.canton
(id, id_provincia, nombre)
VALUES(64, 7, 'SANTA ROSA');
INSERT INTO optica.canton
(id, id_provincia, nombre)
VALUES(65, 7, 'ZARUMA');
INSERT INTO optica.canton
(id, id_provincia, nombre)
VALUES(66, 7, 'LAS LAJAS');
INSERT INTO optica.canton
(id, id_provincia, nombre)
VALUES(67, 8, 'ESMERALDAS');
INSERT INTO optica.canton
(id, id_provincia, nombre)
VALUES(68, 8, 'ELOY ALFARO');
INSERT INTO optica.canton
(id, id_provincia, nombre)
VALUES(69, 8, 'MUISNE');
INSERT INTO optica.canton
(id, id_provincia, nombre)
VALUES(70, 8, 'QUININDÉ');
INSERT INTO optica.canton
(id, id_provincia, nombre)
VALUES(71, 8, 'SAN LORENZO');
INSERT INTO optica.canton
(id, id_provincia, nombre)
VALUES(72, 8, 'ATACAMES');
INSERT INTO optica.canton
(id, id_provincia, nombre)
VALUES(73, 8, 'RIOVERDE');
INSERT INTO optica.canton
(id, id_provincia, nombre)
VALUES(74, 8, 'LA CONCORDIA');
INSERT INTO optica.canton
(id, id_provincia, nombre)
VALUES(75, 9, 'GUAYAQUIL');
INSERT INTO optica.canton
(id, id_provincia, nombre)
VALUES(76, 9, 'ALFREDO BAQUERIZO MORENO (JUJÁN)');
INSERT INTO optica.canton
(id, id_provincia, nombre)
VALUES(77, 9, 'BALAO');
INSERT INTO optica.canton
(id, id_provincia, nombre)
VALUES(78, 9, 'BALZAR');
INSERT INTO optica.canton
(id, id_provincia, nombre)
VALUES(79, 9, 'COLIMES');
INSERT INTO optica.canton
(id, id_provincia, nombre)
VALUES(80, 9, 'DAULE');
INSERT INTO optica.canton
(id, id_provincia, nombre)
VALUES(81, 9, 'DURÁN');
INSERT INTO optica.canton
(id, id_provincia, nombre)
VALUES(82, 9, 'EL EMPALME');
INSERT INTO optica.canton
(id, id_provincia, nombre)
VALUES(83, 9, 'EL TRIUNFO');
INSERT INTO optica.canton
(id, id_provincia, nombre)
VALUES(84, 9, 'MILAGRO');
INSERT INTO optica.canton
(id, id_provincia, nombre)
VALUES(85, 9, 'NARANJAL');
INSERT INTO optica.canton
(id, id_provincia, nombre)
VALUES(86, 9, 'NARANJITO');
INSERT INTO optica.canton
(id, id_provincia, nombre)
VALUES(87, 9, 'PALESTINA');
INSERT INTO optica.canton
(id, id_provincia, nombre)
VALUES(88, 9, 'PEDRO CARBO');
INSERT INTO optica.canton
(id, id_provincia, nombre)
VALUES(89, 9, 'SAMBORONDÓN');
INSERT INTO optica.canton
(id, id_provincia, nombre)
VALUES(90, 9, 'SANTA LUCÍA');
INSERT INTO optica.canton
(id, id_provincia, nombre)
VALUES(91, 9, 'SALITRE (URBINA JADO)');
INSERT INTO optica.canton
(id, id_provincia, nombre)
VALUES(92, 9, 'SAN JACINTO DE YAGUACHI');
INSERT INTO optica.canton
(id, id_provincia, nombre)
VALUES(93, 9, 'PLAYAS');
INSERT INTO optica.canton
(id, id_provincia, nombre)
VALUES(94, 9, 'SIMÓN BOLÍVAR');
INSERT INTO optica.canton
(id, id_provincia, nombre)
VALUES(95, 9, 'CORONEL MARCELINO MARIDUEÑA (SAN CARLOS)');
INSERT INTO optica.canton
(id, id_provincia, nombre)
VALUES(96, 9, 'LOMAS DE SARGENTILLO');
INSERT INTO optica.canton
(id, id_provincia, nombre)
VALUES(97, 9, 'NOBOL');
INSERT INTO optica.canton
(id, id_provincia, nombre)
VALUES(98, 9, 'GENERAL ANTONIO ELIZALDE');
INSERT INTO optica.canton
(id, id_provincia, nombre)
VALUES(99, 9, 'ISIDRO AYORA');
INSERT INTO optica.canton
(id, id_provincia, nombre)
VALUES(100, 10, 'IBARRA');
INSERT INTO optica.canton
(id, id_provincia, nombre)
VALUES(101, 10, 'ANTONIO ANTE');
INSERT INTO optica.canton
(id, id_provincia, nombre)
VALUES(102, 10, 'COTACACHI');
INSERT INTO optica.canton
(id, id_provincia, nombre)
VALUES(103, 10, 'OTAVALO');
INSERT INTO optica.canton
(id, id_provincia, nombre)
VALUES(104, 10, 'PIMAMPIRO');
INSERT INTO optica.canton
(id, id_provincia, nombre)
VALUES(105, 10, 'SAN MIGUEL DE URCUQUÍ');
INSERT INTO optica.canton
(id, id_provincia, nombre)
VALUES(106, 11, 'LOJA');
INSERT INTO optica.canton
(id, id_provincia, nombre)
VALUES(107, 11, 'CALVAS');
INSERT INTO optica.canton
(id, id_provincia, nombre)
VALUES(108, 11, 'CATAMAYO');
INSERT INTO optica.canton
(id, id_provincia, nombre)
VALUES(109, 11, 'CELICA');
INSERT INTO optica.canton
(id, id_provincia, nombre)
VALUES(110, 11, 'CHAGUARPAMBA');
INSERT INTO optica.canton
(id, id_provincia, nombre)
VALUES(111, 11, 'ESPÍNDOLA');
INSERT INTO optica.canton
(id, id_provincia, nombre)
VALUES(112, 11, 'GONZANAMÁ');
INSERT INTO optica.canton
(id, id_provincia, nombre)
VALUES(113, 11, 'MACARÁ');
INSERT INTO optica.canton
(id, id_provincia, nombre)
VALUES(114, 11, 'PALTAS');
INSERT INTO optica.canton
(id, id_provincia, nombre)
VALUES(115, 11, 'PUYANGO');
INSERT INTO optica.canton
(id, id_provincia, nombre)
VALUES(116, 11, 'SARAGURO');
INSERT INTO optica.canton
(id, id_provincia, nombre)
VALUES(117, 11, 'SOZORANGA');
INSERT INTO optica.canton
(id, id_provincia, nombre)
VALUES(118, 11, 'ZAPOTILLO');
INSERT INTO optica.canton
(id, id_provincia, nombre)
VALUES(119, 11, 'PINDAL');
INSERT INTO optica.canton
(id, id_provincia, nombre)
VALUES(120, 11, 'QUILANGA');
INSERT INTO optica.canton
(id, id_provincia, nombre)
VALUES(121, 11, 'OLMEDO');
INSERT INTO optica.canton
(id, id_provincia, nombre)
VALUES(122, 12, 'BABAHOYO');
INSERT INTO optica.canton
(id, id_provincia, nombre)
VALUES(123, 12, 'BABA');
INSERT INTO optica.canton
(id, id_provincia, nombre)
VALUES(124, 12, 'MONTALVO');
INSERT INTO optica.canton
(id, id_provincia, nombre)
VALUES(125, 12, 'PUEBLOVIEJO');
INSERT INTO optica.canton
(id, id_provincia, nombre)
VALUES(126, 12, 'QUEVEDO');
INSERT INTO optica.canton
(id, id_provincia, nombre)
VALUES(127, 12, 'URDANETA');
INSERT INTO optica.canton
(id, id_provincia, nombre)
VALUES(128, 12, 'VENTANAS');
INSERT INTO optica.canton
(id, id_provincia, nombre)
VALUES(129, 12, 'VÍNCES');
INSERT INTO optica.canton
(id, id_provincia, nombre)
VALUES(130, 12, 'PALENQUE');
INSERT INTO optica.canton
(id, id_provincia, nombre)
VALUES(131, 12, 'BUENA FÉ');
INSERT INTO optica.canton
(id, id_provincia, nombre)
VALUES(132, 12, 'VALENCIA');
INSERT INTO optica.canton
(id, id_provincia, nombre)
VALUES(133, 12, 'MOCACHE');
INSERT INTO optica.canton
(id, id_provincia, nombre)
VALUES(134, 12, 'QUINSALOMA');
INSERT INTO optica.canton
(id, id_provincia, nombre)
VALUES(135, 13, 'PORTOVIEJO');
INSERT INTO optica.canton
(id, id_provincia, nombre)
VALUES(136, 13, 'BOLÍVAR');
INSERT INTO optica.canton
(id, id_provincia, nombre)
VALUES(137, 13, 'CHONE');
INSERT INTO optica.canton
(id, id_provincia, nombre)
VALUES(138, 13, 'EL CARMEN');
INSERT INTO optica.canton
(id, id_provincia, nombre)
VALUES(139, 13, 'FLAVIO ALFARO');
INSERT INTO optica.canton
(id, id_provincia, nombre)
VALUES(140, 13, 'JIPIJAPA');
INSERT INTO optica.canton
(id, id_provincia, nombre)
VALUES(141, 13, 'JUNÍN');
INSERT INTO optica.canton
(id, id_provincia, nombre)
VALUES(142, 13, 'MANTA');
INSERT INTO optica.canton
(id, id_provincia, nombre)
VALUES(143, 13, 'MONTECRISTI');
INSERT INTO optica.canton
(id, id_provincia, nombre)
VALUES(144, 13, 'PAJÁN');
INSERT INTO optica.canton
(id, id_provincia, nombre)
VALUES(145, 13, 'PICHINCHA');
INSERT INTO optica.canton
(id, id_provincia, nombre)
VALUES(146, 13, 'ROCAFUERTE');
INSERT INTO optica.canton
(id, id_provincia, nombre)
VALUES(147, 13, 'SANTA ANA');
INSERT INTO optica.canton
(id, id_provincia, nombre)
VALUES(148, 13, 'SUCRE');
INSERT INTO optica.canton
(id, id_provincia, nombre)
VALUES(149, 13, 'TOSAGUA');
INSERT INTO optica.canton
(id, id_provincia, nombre)
VALUES(150, 13, '24 DE MAYO');
INSERT INTO optica.canton
(id, id_provincia, nombre)
VALUES(151, 13, 'PEDERNALES');
INSERT INTO optica.canton
(id, id_provincia, nombre)
VALUES(152, 13, 'OLMEDO');
INSERT INTO optica.canton
(id, id_provincia, nombre)
VALUES(153, 13, 'PUERTO LÓPEZ');
INSERT INTO optica.canton
(id, id_provincia, nombre)
VALUES(154, 13, 'JAMA');
INSERT INTO optica.canton
(id, id_provincia, nombre)
VALUES(155, 13, 'JARAMIJÓ');
INSERT INTO optica.canton
(id, id_provincia, nombre)
VALUES(156, 13, 'SAN VICENTE');
INSERT INTO optica.canton
(id, id_provincia, nombre)
VALUES(157, 14, 'MORONA');
INSERT INTO optica.canton
(id, id_provincia, nombre)
VALUES(158, 14, 'GUALAQUIZA');
INSERT INTO optica.canton
(id, id_provincia, nombre)
VALUES(159, 14, 'LIMÓN INDANZA');
INSERT INTO optica.canton
(id, id_provincia, nombre)
VALUES(160, 14, 'PALORA');
INSERT INTO optica.canton
(id, id_provincia, nombre)
VALUES(161, 14, 'SANTIAGO');
INSERT INTO optica.canton
(id, id_provincia, nombre)
VALUES(162, 14, 'SUCÚA');
INSERT INTO optica.canton
(id, id_provincia, nombre)
VALUES(163, 14, 'HUAMBOYA');
INSERT INTO optica.canton
(id, id_provincia, nombre)
VALUES(164, 14, 'SAN JUAN BOSCO');
INSERT INTO optica.canton
(id, id_provincia, nombre)
VALUES(165, 14, 'TAISHA');
INSERT INTO optica.canton
(id, id_provincia, nombre)
VALUES(166, 14, 'LOGROÑO');
INSERT INTO optica.canton
(id, id_provincia, nombre)
VALUES(167, 14, 'PABLO SEXTO');
INSERT INTO optica.canton
(id, id_provincia, nombre)
VALUES(168, 14, 'TIWINTZA');
INSERT INTO optica.canton
(id, id_provincia, nombre)
VALUES(169, 15, 'TENA');
INSERT INTO optica.canton
(id, id_provincia, nombre)
VALUES(170, 15, 'ARCHIDONA');
INSERT INTO optica.canton
(id, id_provincia, nombre)
VALUES(171, 15, 'EL CHACO');
INSERT INTO optica.canton
(id, id_provincia, nombre)
VALUES(172, 15, 'QUIJOS');
INSERT INTO optica.canton
(id, id_provincia, nombre)
VALUES(173, 15, 'ARLOS JULIO AROSEMENA TOL');
INSERT INTO optica.canton
(id, id_provincia, nombre)
VALUES(174, 16, 'PASTAZA');
INSERT INTO optica.canton
(id, id_provincia, nombre)
VALUES(175, 16, 'MERA');
INSERT INTO optica.canton
(id, id_provincia, nombre)
VALUES(176, 16, 'SANTA CLARA');
INSERT INTO optica.canton
(id, id_provincia, nombre)
VALUES(177, 16, 'ARAJUNO');
INSERT INTO optica.canton
(id, id_provincia, nombre)
VALUES(178, 17, 'QUITO');
INSERT INTO optica.canton
(id, id_provincia, nombre)
VALUES(179, 17, 'CAYAMBE');
INSERT INTO optica.canton
(id, id_provincia, nombre)
VALUES(180, 17, 'MEJIA');
INSERT INTO optica.canton
(id, id_provincia, nombre)
VALUES(181, 17, 'PEDRO MONCAYO');
INSERT INTO optica.canton
(id, id_provincia, nombre)
VALUES(182, 17, 'RUMIÑAHUI');
INSERT INTO optica.canton
(id, id_provincia, nombre)
VALUES(183, 17, 'SAN MIGUEL DE LOS BANCOS');
INSERT INTO optica.canton
(id, id_provincia, nombre)
VALUES(184, 17, 'PEDRO VICENTE MALDONADO');
INSERT INTO optica.canton
(id, id_provincia, nombre)
VALUES(185, 17, 'PUERTO QUITO');
INSERT INTO optica.canton
(id, id_provincia, nombre)
VALUES(186, 18, 'AMBATO');
INSERT INTO optica.canton
(id, id_provincia, nombre)
VALUES(187, 18, 'BAÑOS DE AGUA SANTA');
INSERT INTO optica.canton
(id, id_provincia, nombre)
VALUES(188, 18, 'CEVALLOS');
INSERT INTO optica.canton
(id, id_provincia, nombre)
VALUES(189, 18, 'MOCHA');
INSERT INTO optica.canton
(id, id_provincia, nombre)
VALUES(190, 18, 'PATATE');
INSERT INTO optica.canton
(id, id_provincia, nombre)
VALUES(191, 18, 'QUERO');
INSERT INTO optica.canton
(id, id_provincia, nombre)
VALUES(192, 18, 'SAN PEDRO DE PELILEO');
INSERT INTO optica.canton
(id, id_provincia, nombre)
VALUES(193, 18, 'SANTIAGO DE PÍLLARO');
INSERT INTO optica.canton
(id, id_provincia, nombre)
VALUES(194, 18, 'TISALEO');
INSERT INTO optica.canton
(id, id_provincia, nombre)
VALUES(195, 19, 'ZAMORA');
INSERT INTO optica.canton
(id, id_provincia, nombre)
VALUES(196, 19, 'CHINCHIPE');
INSERT INTO optica.canton
(id, id_provincia, nombre)
VALUES(197, 19, 'NANGARITZA');
INSERT INTO optica.canton
(id, id_provincia, nombre)
VALUES(198, 19, 'YACUAMBI');
INSERT INTO optica.canton
(id, id_provincia, nombre)
VALUES(199, 19, 'YANTZAZA (YANZATZA)');
INSERT INTO optica.canton
(id, id_provincia, nombre)
VALUES(200, 19, 'EL PANGUI');
INSERT INTO optica.canton
(id, id_provincia, nombre)
VALUES(201, 19, 'CENTINELA DEL CÓNDOR');
INSERT INTO optica.canton
(id, id_provincia, nombre)
VALUES(202, 19, 'PALANDA');
INSERT INTO optica.canton
(id, id_provincia, nombre)
VALUES(203, 19, 'PAQUISHA');
INSERT INTO optica.canton
(id, id_provincia, nombre)
VALUES(204, 20, 'SAN CRISTÓBAL');
INSERT INTO optica.canton
(id, id_provincia, nombre)
VALUES(205, 20, 'ISABELA');
INSERT INTO optica.canton
(id, id_provincia, nombre)
VALUES(206, 20, 'SANTA CRUZ');
INSERT INTO optica.canton
(id, id_provincia, nombre)
VALUES(207, 21, 'LAGO AGRIO');
INSERT INTO optica.canton
(id, id_provincia, nombre)
VALUES(208, 21, 'GONZALO PIZARRO');
INSERT INTO optica.canton
(id, id_provincia, nombre)
VALUES(209, 21, 'PUTUMAYO');
INSERT INTO optica.canton
(id, id_provincia, nombre)
VALUES(210, 21, 'SHUSHUFINDI');
INSERT INTO optica.canton
(id, id_provincia, nombre)
VALUES(211, 21, 'SUCUMBÍOS');
INSERT INTO optica.canton
(id, id_provincia, nombre)
VALUES(212, 21, 'CASCALES');
INSERT INTO optica.canton
(id, id_provincia, nombre)
VALUES(213, 21, 'CUYABENO');
INSERT INTO optica.canton
(id, id_provincia, nombre)
VALUES(214, 22, 'ORELLANA');
INSERT INTO optica.canton
(id, id_provincia, nombre)
VALUES(215, 22, 'AGUARICO');
INSERT INTO optica.canton
(id, id_provincia, nombre)
VALUES(216, 22, 'LA JOYA DE LOS SACHAS');
INSERT INTO optica.canton
(id, id_provincia, nombre)
VALUES(217, 22, 'LORETO');
INSERT INTO optica.canton
(id, id_provincia, nombre)
VALUES(218, 23, 'SANTO DOMINGO');
INSERT INTO optica.canton
(id, id_provincia, nombre)
VALUES(219, 24, 'SANTA ELENA');
INSERT INTO optica.canton
(id, id_provincia, nombre)
VALUES(220, 24, 'LA LIBERTAD');
INSERT INTO optica.canton
(id, id_provincia, nombre)
VALUES(221, 24, 'SALINAS');
INSERT INTO optica.canton
(id, id_provincia, nombre)
VALUES(222, 90, 'LAS GOLONDRINAS');
INSERT INTO optica.canton
(id, id_provincia, nombre)
VALUES(223, 90, 'MANGA DEL CURA');
INSERT INTO optica.canton
(id, id_provincia, nombre)
VALUES(224, 90, 'EL PIEDRERO');